# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: 63e2d88b1a2cc22cab6bf9c892839c6c84a935c1

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

mail:
    host: smtp.gmail.com
    port: 587
    username: velmisoff123@gmail.com
    password: slscsdejemrlismc
    protocol: smtp
    tls: true
    auth: true
    from: sellerinterface@terracorp.ru


swagger:
    title: sellerinterface API
    description: sellerinterface applications and beyond!
    version: 0.0.1
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
